import Head from 'next/head'

function About() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <main>
          <h1>
            Welcome to <a href="https://nextjs.org">About</a>
          </h1>
        </main>
      </Head>
    </div>
  )
}

export default About
